// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmhirmoqzuipceblfzfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtaGlybW9xenVpcGNlYmxmemZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMDMwMTUsImV4cCI6MjA3MDg3OTAxNX0.UXGNnX0BIGXoAjhdXOdNA2CMuRQATQA-UBz-i27Ude4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});